SET FOREIGN_KEY_CHECKS = 0;
drop table if exists aisle;
drop table if exists card_reader;
drop table if exists department;
drop table if exists employee;
drop table if exists employee_schedule;
drop table if exists gas_invoice;
drop table if exists gas_supplier;
drop table if exists gas_type;
drop table if exists inventory;
drop table if exists licenses;
drop table if exists management;
drop table if exists partner_business;
drop table if exists payroll;
drop table if exists pump;
drop table if exists product;
drop table if exists product_invoice;
drop table if exists product_supplier;
drop table if exists pump;
drop table if exists pump_gas_type_assoc;
drop table if exists region;
drop table if exists resevoir;
drop table if exists rewards_program_account;
drop table if exists store;
SET FOREIGN_KEY_CHECKS = 1;